version: '3'

services:
  vilnyy-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: vilnyy-app
    restart: always 
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - vilnyy-app-api
networks:
  vilnyy-app-api:
    name: api