version: '3'

services:
  vilnyy-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: vilnyy-app
    restart: always 
    env_file: .env
    ports:
      - $PORT:$PORT
    networks:
      - vilnyy-app-api
networks:
  vilnyy-app-api:
    name: api